services:
  - type: web
    name: sveltekit-bun
    env: node
    buildCommand: curl -fsSL https://bun.sh/install | bash; npm install && npm run build
    startCommand: ./opt/render/.bun/bin/bun build/index.js
    envVars:
      - key: ORIGIN
        value: https://my.site
      - key: PROTOCOL_HEADER
        value: x-forwarded-proto
      - key: HOST_HEADER
        value: x-forwarded-host
      - key: ADDRESS_HEADER
        value: True-Client-IP